const ADD_FOLLOWED_NAME = "ADD_FOLLOWED_NAME";
const REMOVE_FOLLOWED_NAME = "REMOVE_FOLLOWED_NAME";
const ADD_FOLLOWED_COUNTRY = "ADD_FOLLOWED";
const FOLLOWED_SEARCHED = "FOLLOWED_SEARCHED";
const CLEAR_FOLLOWED_COUNTRIES = "CLEAR_FOLLOWED";

export default {
  ADD_FOLLOWED_NAME,
  REMOVE_FOLLOWED_NAME,
  ADD_FOLLOWED_COUNTRY,
  FOLLOWED_SEARCHED,
  CLEAR_FOLLOWED_COUNTRIES,
};
