export default {
  symbols: [
    {
      symbol: require("../../assets/images/flags/af.png"),
      name: "Afghanistan",
    },
    {
      symbol: require("../../assets/images/flags/ax.png"),
      name: "\u00c5land Islands",
    },
    { symbol: require("../../assets/images/flags/al.png"), name: "Albania" },
    { symbol: require("../../assets/images/flags/dz.png"), name: "Algeria" },
    {
      symbol: require("../../assets/images/flags/as.png"),
      name: "American Samoa",
    },
    { symbol: require("../../assets/images/flags/ad.png"), name: "Andorra" },
    { symbol: require("../../assets/images/flags/ao.png"), name: "Angola" },
    { symbol: require("../../assets/images/flags/ai.png"), name: "Anguilla" },
    { symbol: require("../../assets/images/flags/aq.png"), name: "Antarctica" },
    {
      symbol: require("../../assets/images/flags/ag.png"),
      name: "Antigua and Barbuda",
    },
    { symbol: require("../../assets/images/flags/ar.png"), name: "Argentina" },
    { symbol: require("../../assets/images/flags/am.png"), name: "Armenia" },
    { symbol: require("../../assets/images/flags/aw.png"), name: "Aruba" },
    { symbol: require("../../assets/images/flags/au.png"), name: "Australia" },
    { symbol: require("../../assets/images/flags/at.png"), name: "Austria" },
    { symbol: require("../../assets/images/flags/az.png"), name: "Azerbaijan" },
    { symbol: require("../../assets/images/flags/bs.png"), name: "Bahamas" },
    { symbol: require("../../assets/images/flags/bh.png"), name: "Bahrain" },
    { symbol: require("../../assets/images/flags/bd.png"), name: "Bangladesh" },
    { symbol: require("../../assets/images/flags/bb.png"), name: "Barbados" },
    { symbol: require("../../assets/images/flags/by.png"), name: "Belarus" },
    { symbol: require("../../assets/images/flags/be.png"), name: "Belgium" },
    { symbol: require("../../assets/images/flags/bz.png"), name: "Belize" },
    { symbol: require("../../assets/images/flags/bj.png"), name: "Benin" },
    { symbol: require("../../assets/images/flags/bm.png"), name: "Bermuda" },
    { symbol: require("../../assets/images/flags/bt.png"), name: "Bhutan" },
    {
      symbol: require("../../assets/images/flags/bo.png"),
      name: "Bolivia, Plurinational State of",
    },
    {
      symbol: require("../../assets/images/flags/bq.png"),
      name: "Bonaire, Sint Eustatius and Saba",
    },
    {
      symbol: require("../../assets/images/flags/ba.png"),
      name: "Bosnia and Herzegovina",
    },
    { symbol: require("../../assets/images/flags/bw.png"), name: "Botswana" },
    {
      symbol: require("../../assets/images/flags/bv.png"),
      name: "Bouvet Island",
    },
    { symbol: require("../../assets/images/flags/br.png"), name: "Brazil" },
    {
      symbol: require("../../assets/images/flags/io.png"),
      name: "British Indian Ocean Territory",
    },
    {
      symbol: require("../../assets/images/flags/bn.png"),
      name: "Brunei Darussalam",
    },
    { symbol: require("../../assets/images/flags/bg.png"), name: "Bulgaria" },
    {
      symbol: require("../../assets/images/flags/bf.png"),
      name: "Burkina Faso",
    },
    { symbol: require("../../assets/images/flags/bi.png"), name: "Burundi" },
    { symbol: require("../../assets/images/flags/kh.png"), name: "Cambodia" },
    { symbol: require("../../assets/images/flags/cm.png"), name: "Cameroon" },
    { symbol: require("../../assets/images/flags/ca.png"), name: "Canada" },
    { symbol: require("../../assets/images/flags/cv.png"), name: "Cape Verde" },
    {
      symbol: require("../../assets/images/flags/ky.png"),
      name: "Cayman Islands",
    },
    {
      symbol: require("../../assets/images/flags/cf.png"),
      name: "Central African Republic",
    },
    { symbol: require("../../assets/images/flags/td.png"), name: "Chad" },
    { symbol: require("../../assets/images/flags/cl.png"), name: "Chile" },
    { symbol: require("../../assets/images/flags/cn.png"), name: "China" },
    {
      symbol: require("../../assets/images/flags/cx.png"),
      name: "Christmas Island",
    },
    {
      symbol: require("../../assets/images/flags/cc.png"),
      name: "Cocos (Keeling) Islands",
    },
    { symbol: require("../../assets/images/flags/co.png"), name: "Colombia" },
    { symbol: require("../../assets/images/flags/km.png"), name: "Comoros" },
    { symbol: require("../../assets/images/flags/cg.png"), name: "Congo" },
    {
      symbol: require("../../assets/images/flags/cd.png"),
      name: "Congo, the Democratic Republic of the",
    },
    {
      symbol: require("../../assets/images/flags/ck.png"),
      name: "Cook Islands",
    },
    { symbol: require("../../assets/images/flags/cr.png"), name: "Costa Rica" },
    {
      symbol: require("../../assets/images/flags/ci.png"),
      name: "C\u00f4te d'Ivoire",
    },
    { symbol: require("../../assets/images/flags/hr.png"), name: "Croatia" },
    { symbol: require("../../assets/images/flags/cu.png"), name: "Cuba" },
    {
      symbol: require("../../assets/images/flags/cw.png"),
      name: "Cura\u00e7ao",
    },
    { symbol: require("../../assets/images/flags/cy.png"), name: "Cyprus" },
    {
      symbol: require("../../assets/images/flags/cz.png"),
      name: "Czechia",
    },
    { symbol: require("../../assets/images/flags/dk.png"), name: "Denmark" },
    { symbol: require("../../assets/images/flags/dj.png"), name: "Djibouti" },
    { symbol: require("../../assets/images/flags/dm.png"), name: "Dominica" },
    {
      symbol: require("../../assets/images/flags/do.png"),
      name: "Dominican Republic",
    },
    { symbol: require("../../assets/images/flags/ec.png"), name: "Ecuador" },
    { symbol: require("../../assets/images/flags/eg.png"), name: "Egypt" },
    {
      symbol: require("../../assets/images/flags/sv.png"),
      name: "El Salvador",
    },
    {
      symbol: require("../../assets/images/flags/gq.png"),
      name: "Equatorial Guinea",
    },
    { symbol: require("../../assets/images/flags/er.png"), name: "Eritrea" },
    { symbol: require("../../assets/images/flags/ee.png"), name: "Estonia" },
    { symbol: require("../../assets/images/flags/et.png"), name: "Ethiopia" },
    {
      symbol: require("../../assets/images/flags/fk.png"),
      name: "Falkland Islands (Malvinas)",
    },
    {
      symbol: require("../../assets/images/flags/fo.png"),
      name: "Faroe Islands",
    },
    { symbol: require("../../assets/images/flags/fj.png"), name: "Fiji" },
    { symbol: require("../../assets/images/flags/fi.png"), name: "Finland" },
    { symbol: require("../../assets/images/flags/fr.png"), name: "France" },
    {
      symbol: require("../../assets/images/flags/gf.png"),
      name: "French Guiana",
    },
    {
      symbol: require("../../assets/images/flags/pf.png"),
      name: "French Polynesia",
    },
    {
      symbol: require("../../assets/images/flags/tf.png"),
      name: "French Southern Territories",
    },
    { symbol: require("../../assets/images/flags/ga.png"), name: "Gabon" },
    { symbol: require("../../assets/images/flags/gm.png"), name: "Gambia" },
    { symbol: require("../../assets/images/flags/ge.png"), name: "Georgia" },
    { symbol: require("../../assets/images/flags/de.png"), name: "Germany" },
    { symbol: require("../../assets/images/flags/gh.png"), name: "Ghana" },
    { symbol: require("../../assets/images/flags/gi.png"), name: "Gibraltar" },
    { symbol: require("../../assets/images/flags/gr.png"), name: "Greece" },
    { symbol: require("../../assets/images/flags/gl.png"), name: "Greenland" },
    { symbol: require("../../assets/images/flags/gd.png"), name: "Grenada" },
    { symbol: require("../../assets/images/flags/gp.png"), name: "Guadeloupe" },
    { symbol: require("../../assets/images/flags/gu.png"), name: "Guam" },
    { symbol: require("../../assets/images/flags/gt.png"), name: "Guatemala" },
    { symbol: require("../../assets/images/flags/gg.png"), name: "Guernsey" },
    { symbol: require("../../assets/images/flags/gn.png"), name: "Guinea" },
    {
      symbol: require("../../assets/images/flags/gw.png"),
      name: "Guinea-Bissau",
    },
    { symbol: require("../../assets/images/flags/gy.png"), name: "Guyana" },
    { symbol: require("../../assets/images/flags/ht.png"), name: "Haiti" },
    {
      symbol: require("../../assets/images/flags/hm.png"),
      name: "Heard Island and McDonald Islands",
    },
    {
      symbol: require("../../assets/images/flags/va.png"),
      name: "Holy See (Vatican City State)",
    },
    { symbol: require("../../assets/images/flags/hn.png"), name: "Honduras" },
    { symbol: require("../../assets/images/flags/hk.png"), name: "Hong Kong" },
    { symbol: require("../../assets/images/flags/hu.png"), name: "Hungary" },
    { symbol: require("../../assets/images/flags/is.png"), name: "Iceland" },
    { symbol: require("../../assets/images/flags/in.png"), name: "India" },
    { symbol: require("../../assets/images/flags/id.png"), name: "Indonesia" },
    {
      symbol: require("../../assets/images/flags/ir.png"),
      name: "Iran, Islamic Republic of",
    },
    { symbol: require("../../assets/images/flags/iq.png"), name: "Iraq" },
    { symbol: require("../../assets/images/flags/ie.png"), name: "Ireland" },
    {
      symbol: require("../../assets/images/flags/im.png"),
      name: "Isle of Man",
    },
    { symbol: require("../../assets/images/flags/il.png"), name: "Israel" },
    { symbol: require("../../assets/images/flags/it.png"), name: "Italy" },
    { symbol: require("../../assets/images/flags/jm.png"), name: "Jamaica" },
    { symbol: require("../../assets/images/flags/jp.png"), name: "Japan" },
    { symbol: require("../../assets/images/flags/je.png"), name: "Jersey" },
    { symbol: require("../../assets/images/flags/jo.png"), name: "Jordan" },
    { symbol: require("../../assets/images/flags/kz.png"), name: "Kazakhstan" },
    { symbol: require("../../assets/images/flags/ke.png"), name: "Kenya" },
    { symbol: require("../../assets/images/flags/ki.png"), name: "Kiribati" },
    {
      symbol: require("../../assets/images/flags/kp.png"),
      name: "Korea, Democratic People's Republic of",
    },
    {
      symbol: require("../../assets/images/flags/kr.png"),
      name: "Korea, Republic of",
    },
    { symbol: require("../../assets/images/flags/kw.png"), name: "Kuwait" },
    { symbol: require("../../assets/images/flags/kg.png"), name: "Kyrgyzstan" },
    {
      symbol: require("../../assets/images/flags/la.png"),
      name: "Lao People's Democratic Republic",
    },
    { symbol: require("../../assets/images/flags/lv.png"), name: "Latvia" },
    { symbol: require("../../assets/images/flags/lb.png"), name: "Lebanon" },
    { symbol: require("../../assets/images/flags/ls.png"), name: "Lesotho" },
    { symbol: require("../../assets/images/flags/lr.png"), name: "Liberia" },
    { symbol: require("../../assets/images/flags/ly.png"), name: "Libya" },
    {
      symbol: require("../../assets/images/flags/li.png"),
      name: "Liechtenstein",
    },
    { symbol: require("../../assets/images/flags/lt.png"), name: "Lithuania" },
    { symbol: require("../../assets/images/flags/lu.png"), name: "Luxembourg" },
    { symbol: require("../../assets/images/flags/mo.png"), name: "Macao" },
    {
      symbol: require("../../assets/images/flags/mk.png"),
      name: "Macedonia, the Former Yugoslav Republic of",
    },
    { symbol: require("../../assets/images/flags/mg.png"), name: "Madagascar" },
    { symbol: require("../../assets/images/flags/mw.png"), name: "Malawi" },
    { symbol: require("../../assets/images/flags/my.png"), name: "Malaysia" },
    { symbol: require("../../assets/images/flags/mv.png"), name: "Maldives" },
    { symbol: require("../../assets/images/flags/ml.png"), name: "Mali" },
    { symbol: require("../../assets/images/flags/mt.png"), name: "Malta" },
    {
      symbol: require("../../assets/images/flags/mh.png"),
      name: "Marshall Islands",
    },
    { symbol: require("../../assets/images/flags/mq.png"), name: "Martinique" },
    { symbol: require("../../assets/images/flags/mr.png"), name: "Mauritania" },
    { symbol: require("../../assets/images/flags/mu.png"), name: "Mauritius" },
    { symbol: require("../../assets/images/flags/yt.png"), name: "Mayotte" },
    { symbol: require("../../assets/images/flags/mx.png"), name: "Mexico" },
    {
      symbol: require("../../assets/images/flags/fm.png"),
      name: "Micronesia, Federated States of",
    },
    {
      symbol: require("../../assets/images/flags/md.png"),
      name: "Moldova, Republic of",
    },
    { symbol: require("../../assets/images/flags/mc.png"), name: "Monaco" },
    { symbol: require("../../assets/images/flags/mn.png"), name: "Mongolia" },
    { symbol: require("../../assets/images/flags/me.png"), name: "Montenegro" },
    { symbol: require("../../assets/images/flags/ms.png"), name: "Montserrat" },
    { symbol: require("../../assets/images/flags/ma.png"), name: "Morocco" },
    { symbol: require("../../assets/images/flags/mz.png"), name: "Mozambique" },
    { symbol: require("../../assets/images/flags/mm.png"), name: "Myanmar" },
    { symbol: require("../../assets/images/flags/na.png"), name: "Namibia" },
    { symbol: require("../../assets/images/flags/nr.png"), name: "Nauru" },
    { symbol: require("../../assets/images/flags/np.png"), name: "Nepal" },
    {
      symbol: require("../../assets/images/flags/nl.png"),
      name: "Netherlands",
    },
    {
      symbol: require("../../assets/images/flags/nc.png"),
      name: "New Caledonia",
    },
    {
      symbol: require("../../assets/images/flags/nz.png"),
      name: "New Zealand",
    },
    { symbol: require("../../assets/images/flags/ni.png"), name: "Nicaragua" },
    { symbol: require("../../assets/images/flags/ne.png"), name: "Niger" },
    { symbol: require("../../assets/images/flags/ng.png"), name: "Nigeria" },
    { symbol: require("../../assets/images/flags/nu.png"), name: "Niue" },
    {
      symbol: require("../../assets/images/flags/nf.png"),
      name: "Norfolk Island",
    },
    {
      symbol: require("../../assets/images/flags/mp.png"),
      name: "Northern Mariana Islands",
    },
    { symbol: require("../../assets/images/flags/no.png"), name: "Norway" },
    { symbol: require("../../assets/images/flags/om.png"), name: "Oman" },
    { symbol: require("../../assets/images/flags/pk.png"), name: "Pakistan" },
    { symbol: require("../../assets/images/flags/pw.png"), name: "Palau" },
    {
      symbol: require("../../assets/images/flags/ps.png"),
      name: "Palestine, State of",
    },
    { symbol: require("../../assets/images/flags/pa.png"), name: "Panama" },
    {
      symbol: require("../../assets/images/flags/pg.png"),
      name: "Papua New Guinea",
    },
    { symbol: require("../../assets/images/flags/py.png"), name: "Paraguay" },
    { symbol: require("../../assets/images/flags/pe.png"), name: "Peru" },
    {
      symbol: require("../../assets/images/flags/ph.png"),
      name: "Philippines",
    },
    { symbol: require("../../assets/images/flags/pn.png"), name: "Pitcairn" },
    { symbol: require("../../assets/images/flags/pl.png"), name: "Poland" },
    { symbol: require("../../assets/images/flags/pt.png"), name: "Portugal" },
    {
      symbol: require("../../assets/images/flags/pr.png"),
      name: "Puerto Rico",
    },
    { symbol: require("../../assets/images/flags/qa.png"), name: "Qatar" },
    {
      symbol: require("../../assets/images/flags/re.png"),
      name: "R\u00e9union",
    },
    { symbol: require("../../assets/images/flags/ro.png"), name: "Romania" },
    {
      symbol: require("../../assets/images/flags/ru.png"),
      name: "Russian Federation",
    },
    { symbol: require("../../assets/images/flags/rw.png"), name: "Rwanda" },
    {
      symbol: require("../../assets/images/flags/bl.png"),
      name: "Saint Barth\u00e9lemy",
    },
    {
      symbol: require("../../assets/images/flags/sh.png"),
      name: "Saint Helena, Ascension and Tristan da Cunha",
    },
    {
      symbol: require("../../assets/images/flags/kn.png"),
      name: "Saint Kitts and Nevis",
    },
    {
      symbol: require("../../assets/images/flags/lc.png"),
      name: "Saint Lucia",
    },
    {
      symbol: require("../../assets/images/flags/mf.png"),
      name: "Saint Martin (French part)",
    },
    {
      symbol: require("../../assets/images/flags/pm.png"),
      name: "Saint Pierre and Miquelon",
    },
    {
      symbol: require("../../assets/images/flags/vc.png"),
      name: "Saint Vincent and the Grenadines",
    },
    { symbol: require("../../assets/images/flags/ws.png"), name: "Samoa" },
    { symbol: require("../../assets/images/flags/sm.png"), name: "San Marino" },
    {
      symbol: require("../../assets/images/flags/st.png"),
      name: "Sao Tome and Principe",
    },
    {
      symbol: require("../../assets/images/flags/sa.png"),
      name: "Saudi Arabia",
    },
    { symbol: require("../../assets/images/flags/sn.png"), name: "Senegal" },
    { symbol: require("../../assets/images/flags/rs.png"), name: "Serbia" },
    { symbol: require("../../assets/images/flags/sc.png"), name: "Seychelles" },
    {
      symbol: require("../../assets/images/flags/sl.png"),
      name: "Sierra Leone",
    },
    { symbol: require("../../assets/images/flags/sg.png"), name: "Singapore" },
    {
      symbol: require("../../assets/images/flags/sx.png"),
      name: "Sint Maarten (Dutch part)",
    },
    { symbol: require("../../assets/images/flags/sk.png"), name: "Slovakia" },
    { symbol: require("../../assets/images/flags/si.png"), name: "Slovenia" },
    {
      symbol: require("../../assets/images/flags/sb.png"),
      name: "Solomon Islands",
    },
    { symbol: require("../../assets/images/flags/so.png"), name: "Somalia" },
    {
      symbol: require("../../assets/images/flags/za.png"),
      name: "South Africa",
    },
    {
      symbol: require("../../assets/images/flags/gs.png"),
      name: "South Georgia and the South Sandwich Islands",
    },
    {
      symbol: require("../../assets/images/flags/ss.png"),
      name: "South Sudan",
    },
    { symbol: require("../../assets/images/flags/es.png"), name: "Spain" },
    { symbol: require("../../assets/images/flags/lk.png"), name: "Sri Lanka" },
    { symbol: require("../../assets/images/flags/sd.png"), name: "Sudan" },
    { symbol: require("../../assets/images/flags/sr.png"), name: "Suriname" },
    {
      symbol: require("../../assets/images/flags/sj.png"),
      name: "Svalbard and Jan Mayen",
    },
    { symbol: require("../../assets/images/flags/sz.png"), name: "Swaziland" },
    { symbol: require("../../assets/images/flags/se.png"), name: "Sweden" },
    {
      symbol: require("../../assets/images/flags/ch.png"),
      name: "Switzerland",
    },
    {
      symbol: require("../../assets/images/flags/sy.png"),
      name: "Syrian Arab Republic",
    },
    {
      symbol: require("../../assets/images/flags/tw.png"),
      name: "Taiwan, Province of China",
    },
    { symbol: require("../../assets/images/flags/tj.png"), name: "Tajikistan" },
    {
      symbol: require("../../assets/images/flags/tz.png"),
      name: "Tanzania, United Republic of",
    },
    { symbol: require("../../assets/images/flags/th.png"), name: "Thailand" },
    {
      symbol: require("../../assets/images/flags/tl.png"),
      name: "Timor-Leste",
    },
    { symbol: require("../../assets/images/flags/tg.png"), name: "Togo" },
    { symbol: require("../../assets/images/flags/tk.png"), name: "Tokelau" },
    { symbol: require("../../assets/images/flags/to.png"), name: "Tonga" },
    {
      symbol: require("../../assets/images/flags/tt.png"),
      name: "Trinidad and Tobago",
    },
    { symbol: require("../../assets/images/flags/tn.png"), name: "Tunisia" },
    { symbol: require("../../assets/images/flags/tr.png"), name: "Turkey" },
    {
      symbol: require("../../assets/images/flags/tm.png"),
      name: "Turkmenistan",
    },
    {
      symbol: require("../../assets/images/flags/tc.png"),
      name: "Turks and Caicos Islands",
    },
    { symbol: require("../../assets/images/flags/tv.png"), name: "Tuvalu" },
    { symbol: require("../../assets/images/flags/ug.png"), name: "Uganda" },
    { symbol: require("../../assets/images/flags/ua.png"), name: "Ukraine" },
    {
      symbol: require("../../assets/images/flags/ae.png"),
      name: "United Arab Emirates",
    },
    {
      symbol: require("../../assets/images/flags/gb.png"),
      name: "United Kingdom",
    },
    {
      symbol: require("../../assets/images/flags/us.png"),
      name: "US",
    },
    {
      symbol: require("../../assets/images/flags/um.png"),
      name: "United States Minor Outlying Islands",
    },
    { symbol: require("../../assets/images/flags/uy.png"), name: "Uruguay" },
    { symbol: require("../../assets/images/flags/uz.png"), name: "Uzbekistan" },
    { symbol: require("../../assets/images/flags/vu.png"), name: "Vanuatu" },
    {
      symbol: require("../../assets/images/flags/ve.png"),
      name: "Venezuela, Bolivarian Republic of",
    },
    { symbol: require("../../assets/images/flags/vn.png"), name: "Viet Nam" },
    {
      symbol: require("../../assets/images/flags/vg.png"),
      name: "Virgin Islands, British",
    },
    {
      symbol: require("../../assets/images/flags/vi.png"),
      name: "Virgin Islands, U.S.",
    },
    {
      symbol: require("../../assets/images/flags/wf.png"),
      name: "Wallis and Futuna",
    },
    {
      symbol: require("../../assets/images/flags/eh.png"),
      name: "Western Sahara",
    },
    { symbol: require("../../assets/images/flags/ye.png"), name: "Yemen" },
    { symbol: require("../../assets/images/flags/zm.png"), name: "Zambia" },
    { symbol: require("../../assets/images/flags/zw.png"), name: "Zimbabwe" },
  ],
};
