const ADD_SEARCHED = "ADD_SEARCHED";
const CLEAR_SEARCHED_COUNTRIES = "CLEAR_SEARCHED";
const COUNTRIES_SEARCHED = "SEARCHED";

export default {
  ADD_SEARCHED,
  CLEAR_SEARCHED_COUNTRIES,
  COUNTRIES_SEARCHED,
};
